apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq-server-config
  namespace: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # ปรับขนาดตามที่ต้องการ
  storageClassName: standard
