replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/rabbitmq
  tag: 3.11.2
  pullPolicy: IfNotPresent

auth:
  username: admin 
  password: admin
  erlangCookie: secretcookie

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 8Gi

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "backend-themis-rabbitmq-server"

service:
  type: NodePort
  port: 5672
  managerPort: 15672

secrets:
  rabbitmqUsername: myuser
  rabbitmqPassword: mypassword


ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  ENV: dev

rabbitmq:
  extraPlugins: |
    [rabbitmq_management].

