apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ include "rabbitmq.name" . }}
    chart: {{ include "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  rabbitmq.conf: |
    log.console = true
    log.console.level = info
    management.load_definitions = /app/load_definition.json
