apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-themis-rabbitmq-server.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rabbitmq-username: {{ .Values.secrets.rabbitmqUsername | b64enc | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmqPassword | b64enc | quote }}
