apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app: {{ include "rabbitmq.name" . }}
    chart: {{ include "rabbitmq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      name: tcp
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
    - port: {{ .Values.service.managerPort }}
      protocol: TCP
      name: manager
      targetPort: {{ .Values.service.managerTargetPort }}
  selector:
    app: {{ include "rabbitmq.name" . }}
    release: {{ .Release.Name }}
